#!/bin/bash -x

CONF="$1"
CLUSTER_ENV="$2"
CURRENT_CONTEXT="$(yq r "$CONF" current-context)"
CONTEXT_INDEX="$(yq r "$CONF" contexts.*.name | awk -v "name=$CURRENT_CONTEXT" '$2 == name {print NR -1}')"
NAME="$(yq r "$CONF" contexts.["$CONTEXT_INDEX"].context.cluster)"
CLUSTER_INDEX="$(yq r "$CONF" clusters.*.name | awk -v "name=$NAME" '$2 == name {print NR -1}')"
APIURL="$(yq r "$CONF" clusters["$CLUSTER_INDEX"].cluster.server)"
APIHOST=$(echo $APIURL | sed -e 's/.*\/\/\([^:]\+\).*/\1/g')
DOMAIN=${APIHOST#*.}
BASE_DOMAIN=${DOMAIN#*.}
cat << EOF | tee "$CLUSTER_ENV"
NAME="$NAME"
APIURL="$APIURL"
APIHOST="$APIHOST"
DOMAIN="$DOMAIN"
BASE_DOMAIN="$BASE_DOMAIN"
EOF
